apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.spring.labels }}-service"
  labels:
    app: "{{ .Values.spring.labels }}"

spec:
  selector:
    app: "{{ .Values.spring.labels }}"
  ports:
    - protocol: TCP
      port: {{ .Values.spring.service.port }}
      targetPort: {{ .Values.spring.service.advertise.port }}
